### ISSUE TITLE
Get our hands on (or create if need be) scans of Xu 2007 and Mou & Zhong 2017

### ISSUE THREAD

**Issue by nh36** [hanproj/hanproject#10]
*Xu, Z. 2007. 漢代銅器銘文綜合研究. Beijing: 作家出版社.
https://library.soas.ac.uk/Record/10435549
*Mou, H. & Zhong, G. 2017. 漢金文輯校. Beijing: 光明日報出版社.
https://library.soas.ac.uk/Record/10435550

**Comment by ashhenson** [comment]
We have the scans.
