### ISSUE TITLE
WP2 task 2: OCR relevant rhymed texts from Xu 2007. (R)

### ISSUE THREAD

**Issue by nh36** [hanproj/hanproject#6]
- [x] Mou, H. & Zhong, G. 2017. 漢金文輯校. Beijing: 光明日報出版社.
- [x] Lu Q. 1983. 先秦漢魏晉南北朝詩. Beijing: 中華書局.
- [x]  Mao Y. 2008. 漢魏六朝碑刻校註. Beijing: 綫裝書局.
- [x] Hayashi, H. 2015. 漢三国西晉鏡銘集成. Yokohama: 横浜ユーラシア文化館.

**Comment by ashhenson** [comment]
We have OCRed data for Lu Q. 1983. 先秦漢魏晉南北朝詩.

**Comment by nh36** [comment]
Some amazing news. My friend Jiyue at Renda has passed to me all rhymed stelae from Mao Y. 2008. 漢魏六朝碑刻校註. Beijing: 綫裝書局 as typed off by his friend Zhang Yuzhuo 张愉卓. The data is now here https://github.com/hanproj/stelae/tree/main/raw

**Comment by nh36** [comment]
Other good news, the Hayashi 2015 is born digital, so I just resaved the .pdf as .docx and .txt. It is here https://github.com/hanproj/mirrors/tree/main/raw

**Comment by nh36** [comment]
I have OCRed "Mou, H. & Zhong, G. 2017. 漢金文輯校. Beijing: 光明日報出版社." using Abbyy FineReader. The results look good to me, but they need to be checked more carefully for overall usability. I think Abbyy is going to work better than Google. I note that Abbyy also has an API, which will naturally be better than the personal version. If the quality we got isn't good enough, we could try the API.

**Comment by nh36** [comment]
Forgot to ask you about this. So, my sense is that we don't really need this book for nothing.

- Xu, Z. 2007. 漢代銅器銘文綜合研究. Beijing: 作家出版社.

I would be grateful if you could just second this, so I can cross it off of a to-do list.

**Comment by ecaldwell4** [comment]
Not directly relevant to the current project. 

Sincerely,

Dr Ernest Caldwell
